import "./styles/globals.scss";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import Navigation from "./components/layout/Navigation";
import Footer from "./components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: {
    name: "Arnold Truong",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col gap-4`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
