import "../styles/globals.scss";
import { Inter, Playfair_Display, Lora } from "next/font/google";
import { Metadata } from "next";
import Navigation from "../components/layout/Navigation";
import Footer from "../components/layout/Footer";
import PageContainer from "../components/layout/PageContainer";
import Provider from "../services/redux/Provider";

const inter = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: {
    name: "Arnold Truong",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col gap-4`}>
        <Provider>
          <Navigation />
          <PageContainer>{children}</PageContainer>
          <PageContainer>
            <Footer />
          </PageContainer>
        </Provider>
      </body>
    </html>
  );
}
